name: Export MATLAB Live Script
on: [push]
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Export Notebook
        uses: matlab-actions/run-command@v2
        with:
          command: matlab.internal.liveeditor.openAndConvert('force_transformation_v2.mlx', 'force_transformation_v2.md')
